# Ejercicios de practica Numpy


Crear un array de ceros


In [1]:
import numpy as np

Ejercicio: Crea un array de una dimensión con 10 ceros.
Hint: Usa np.zeros().


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Crear un array de unos
Ejercicio: Crea un array de una dimensión con 10 unos.

In [3]:
np.zeros(10)+1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Crear un array de valores enteros del 10 al 49. 

Ejercicio: Crea un array que contenga los números enteros del 10 al 49, inclusive.
Hint: Usa np.arange().

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Invertir un array
Ejercicio: Invierte el array del ejercicio anterior (10 al 49).


In [5]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

Crear una matriz 3x3 con valores del 0 al 8
Ejercicio: Crea una matriz 3x3 con valores que van del 0 al 8.
Hint: Usa np.arange() y .reshape().



In [6]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Encontrar los índices de los elementos diferentes de cero
Ejercicio: Dado el array [1, 2, 0, 0, 4, 0], encuentra los índices de los elementos que no son cero.
Hint: Usa np.nonzero().

In [7]:
arr = np.array([1,2,0,0,4,0])
arr


array([1, 2, 0, 0, 4, 0])

In [8]:
nonzero = np.nonzero(arr)
nonzero

(array([0, 1, 4]),)

Crear una matriz identidad
Ejercicio: Crea una matriz identidad de 3x3.
Hint: Usa np.eye() o np.identity().


In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Crear un array de números aleatorios
Ejercicio: Crea un array de 10 números aleatorios entre 0 y 1.
Hint: Usa np.random.random().


In [10]:
np.random.random(10)

array([0.28281298, 0.31298276, 0.8877193 , 0.3382657 , 0.98345995,
       0.13240233, 0.46629191, 0.27414456, 0.0682831 , 0.61487614])

Crear una matriz aleatoria y encontrar los valores mínimo y máximo
Ejercicio: Crea una matriz 4x4 con valores aleatorios y encuentra el valor mínimo y el máximo.
Hint: Usa np.random.random() y np.min()/np.max().



In [11]:
np.linspace(1,16,16).reshape(4,4)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [12]:
mat = np.random.random(16).reshape(4,4)
print(mat.min())
print(mat.max())
media = np.mean(mat)

0.03246720358132049
0.9231078960035821


Calcular la media de un array
Ejercicio: Crea un array de 10 números aleatorios y calcula su media.
Hint: Usa np.mean().


In [13]:
array10 = np.arange(10, 20)
array10
np.mean(array10)

np.float64(14.5)

Nivel Avanzado
Crear una matriz 5x5 con valores de 1 a 25
Ejercicio: Crea una matriz 5x5 que contenga valores enteros del 1 al 25.
Hint: Usa np.arange() y .reshape().



In [14]:
matriz = np.arange(1,26).reshape(5,5)
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Extraer una submatriz de una matriz 5x5
Ejercicio: A partir de la matriz del ejercicio anterior, extrae la submatriz central 3x3.
Hint: Usa slicing.

In [15]:
submatriz = matriz[1:4, 1:4]
submatriz

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

Normalizar una matriz
Ejercicio: Crea una matriz de valores aleatorios y normalízala para que sus valores estén entre 0 y 1.
Hint: Usa (matriz - np.min()) / (np.max() - np.min()).


In [16]:
min = matriz.min()
max = matriz.max ()
matriz_normalizada = (matriz-min) / (matriz-max)
print(matriz_normalizada)

[[ -0.          -0.04347826  -0.09090909  -0.14285714  -0.2       ]
 [ -0.26315789  -0.33333333  -0.41176471  -0.5         -0.6       ]
 [ -0.71428571  -0.84615385  -1.          -1.18181818  -1.4       ]
 [ -1.66666667  -2.          -2.42857143  -3.          -3.8       ]
 [ -5.          -7.         -11.         -23.                  inf]]


/var/folders/3k/lkz67hk967s8dvyhg9zrqdz80000gn/T/ipykernel_7933/898278133.py:3: RuntimeWarning: divide by zero encountered in divide
  matriz_normalizada = (matriz-min) / (matriz-max)


Multiplicación de matrices
Ejercicio: Crea dos matrices 3x3 y realiza su multiplicación (no multiplicación elemento a elemento).
Hint: Usa np.dot() o @.


In [17]:
matriz1 = np.random.random(9).reshape(3,3)
matriz2 = np.arange(20,29).reshape(3,3)
print(matriz1)
print(matriz2)

multiplicacion = np.dot(matriz1, matriz2)
print(multiplicacion)

[[0.17922122 0.02957334 0.93747249]
 [0.50036094 0.72611817 0.69819639]
 [0.92464339 0.36033535 0.02120767]]
[[20 21 22]
 [23 24 25]
 [26 27 28]]
[[28.63889597 29.78516302 30.93143007]
 [44.8610429  46.78571841 48.71039391]
 [27.33198017 28.63816657 29.94435298]]


Encontrar el valor más cercano en un array
Ejercicio: Dado un array de 100 números aleatorios y un número aleatorio, encuentra el valor en el array que sea más cercano a ese número.
Hint: Usa np.abs() y np.argmin().

In [18]:
ar = np.random.random(100)*100
print(ar)
num = np.random.random(1)*100
print(num)
# Encontrar las diferencias absolutas entre el número aleatorio y los valores del array
diferencias = np.abs(ar - num)

# Encontrar el índice del valor más cercano
indice_valor_cercano = np.argmin(diferencias)

# Obtener el valor más cercano en el array
valor_cercano = ar[indice_valor_cercano]

print("\nEl valor más cercano en el array es:", valor_cercano)

[33.80401279 75.91670576 47.1535275  19.59892542 58.12150469 77.75793893
 43.81253278 75.82230902  1.27813018 47.73093708 89.94218432 54.83773321
  5.29039007 68.68373277 91.40011284 35.21774402 16.46497779  5.70867462
  3.37164575 97.45333776  5.07384676 94.93550099 53.97170682 28.20850063
  3.04203858 37.39686212 50.68602681 37.10254883 90.78838456 94.82227863
 88.64579093 95.86636219 39.62174651 56.37321107 18.85044723 20.61521122
 54.07874721  1.48589478 71.4161475  26.28790033 11.26255039  2.89665343
 92.07429734 88.53820684 79.47762093 76.05019671 58.77207546 96.77803244
 76.84381146 90.64272489 68.75817298 34.84423791 19.03779936 89.26232881
 13.4315969  63.85093801 83.17062696 52.72916002 78.95766704 39.86464358
 64.78518586 79.88340715 34.54720789 48.93886955 16.19993961 78.4403281
 66.40015514 40.29896658 43.58079995 67.89960738  2.36063393 38.41736006
 40.12615177  7.1226224  61.84013715  2.87786539 37.18816444  4.09872944
 24.7130553  80.37155562 39.40288378  6.35694794 76.